---
- name: Verify
  hosts: all
  tasks:
  - name: Gather package facts
    package_facts:
      manager: auto
  - name: Verify Packages
    assert:
      that: "'{{ item }}' in ansible_facts.packages"
    with_items:
      - python

- name: Include Shared Verify tasks
  import_playbook: ../../tests/shared_tests.yml